# Generated by Django 4.0.4 on 2022-06-30 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pub_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 20, 16, 33, 433586, tzinfo=utc), verbose_name='date published'),
        ),
    ]
