# Generated by Django 4.0.4 on 2022-07-02 13:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Videos', '0003_alter_video_path_name_alter_video_pub_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='num_of_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='num_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='path_name',
            field=models.FileField(upload_to='Videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 52, 31, 49957, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 52, 31, 49957, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 52, 31, 50958, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Videos.video')),
            ],
        ),
    ]
