# Generated by Django 4.0.4 on 2022-07-03 09:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0004_video_num_of_dislikes_video_num_of_likes_video_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 9, 47, 59, 531890, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 9, 47, 59, 530889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 9, 47, 59, 530889, tzinfo=utc), verbose_name='date published'),
        ),
    ]
