# Generated by Django 4.0.4 on 2022-07-12 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Videos', '0006_alter_comments_date_alter_like_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.ImageField(default='previews/base_preview.jpg', upload_to='previews/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='path_name',
            field=models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
